layout_spectrum: 1
color:
  saturation: 0.9784946
  brandStrength: 0.7610235
  lightness: 0.6702509
  rhythmicContrast: 1
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
typography_spectrum: 1
name: The Future Becomes
